apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin-rh-case-03544800
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/stats
      - nodes/proxy
    verbs:
      - get
      - list
      - watch