apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-storage-collector
  namespace: rh-case-03544800
  labels:
    app: builds-pods-storage-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builds-pods-storage-collector
  template:
    metadata:
      labels:
        app: builds-pods-storage-collector
    spec:
      serviceAccountName: builds-pods-storage-collector
      serviceAccount: builds-pods-storage-collector
      containers:
      - name: builds-pods-storage-collector
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3419113034d82047e5fe993821bf5027c0b436f41121898ea534a1b116534687
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            set -euo pipefail
            trap 'jobs -p | xargs -r kill; exit 0' TERM
            while true; do oc get node -l node-role.kubernetes.io/worker= -o json| jq '.items[].metadata.name' -r | while read NODE; do oc get --raw /api/v1/nodes/${NODE}/proxy/stats/summary  | jq --arg nodeName $NODE --arg dateTime date '.pods[] | . as $parent | select($parent.podRef.name| contains("build")) | "{\"Node\": \"" + $nodeName + "\", \"Namespace\": \"" + $parent.podRef.namespace + "\"," + " \"PodName\": \"" + $parent.podRef.name + "\"," + " \"UsedGB\": \"" + ($parent."ephemeral-storage".usedBytes/1024/1024/1024|tostring) + "\"}"' -r; done && sleep 15; done
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi