apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-storage-collector
  namespace: rh-case-03544800
  labels:
    app: builds-pods-storage-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builds-pods-storage-collector
  template:
    metadata:
      labels:
        app: builds-pods-storage-collector
    spec:
      serviceAccountName: builds-pods-storage-collector
      serviceAccount: builds-pods-storage-collector
      containers:
      - name: builds-pods-storage-collector
        image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3419113034d82047e5fe993821bf5027c0b436f41121898ea534a1b116534687
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - -c
          - |
            set -euo pipefail
            trap 'jobs -p | xargs -r kill; exit 0' TERM
            while true; do sleep 15 && oc get node -l node-role.kubernetes.io/worker= -o json| jq '.items[].metadata.name' -r | while read NODE; do printf "========\nDate     : $(date)\nNode     : $NODE\n" && oc get --raw /api/v1/nodes/${NODE}/proxy/stats/summary  | jq '.pods[] | . as $parent | select($parent.podRef.name| contains("build")) | "Namespace: " + $parent.podRef.namespace + "\n" + "PodName  : " + $parent.podRef.name + "\n" + "UsedGB   : " + ($parent."ephemeral-storage".usedBytes/1024/1024/1024|tostring)' -r; done; done
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi